"""Framework-independent CareerPilot AI core package."""

from careerpilot_core.access import (
    AccessDeniedError,
    AccessPolicy,
    Actor,
    AuthorizationContext,
    Membership,
    Permission,
    PolicyDecision,
    ResourceAttributes,
    Role,
    Tenant,
    TenantKind,
)
from careerpilot_core.audit import AuditEvent, AuditEventDraft, AuditSink
from careerpilot_core.models import (
    Education,
    EvidenceItem,
    EvidenceState,
    Experience,
    JobAnalysis,
    ProfessionalProfile,
    Skill,
)
from careerpilot_core.ports import (
    ExternalIdentity,
    IdentityVerifier,
    MalwareScanner,
    ProfileRepository,
)
from careerpilot_core.rag_service import (
    DeletionConfirmationError,
    DocumentNotFoundError,
    DocumentValidationError,
    RagService,
)
from careerpilot_core.retrieval import (
    Citation,
    DocumentChunk,
    DocumentRecord,
    DocumentStatus,
    InjectionRisk,
    ParsedSection,
    RetrievalCandidate,
    RetrievalResult,
    RetrievedPassage,
    ScanResult,
)
from careerpilot_core.services import (
    CareerJourneyService,
    EvidenceValidationError,
    ProfileConflictError,
    ProfileNotFoundError,
    ProfileValidationError,
)
from careerpilot_core.tooling import (
    ToolCapability,
    ToolErrorCode,
    ToolExecutionError,
    ToolRisk,
)

__all__ = [
    "AccessDeniedError",
    "AccessPolicy",
    "Actor",
    "AuditEvent",
    "AuditEventDraft",
    "AuditSink",
    "AuthorizationContext",
    "CareerJourneyService",
    "Citation",
    "DeletionConfirmationError",
    "DocumentChunk",
    "DocumentNotFoundError",
    "DocumentRecord",
    "DocumentStatus",
    "DocumentValidationError",
    "Education",
    "EvidenceItem",
    "EvidenceState",
    "EvidenceValidationError",
    "Experience",
    "ExternalIdentity",
    "IdentityVerifier",
    "InjectionRisk",
    "JobAnalysis",
    "MalwareScanner",
    "Membership",
    "ParsedSection",
    "Permission",
    "PolicyDecision",
    "ProfessionalProfile",
    "ProfileConflictError",
    "ProfileNotFoundError",
    "ProfileRepository",
    "ProfileValidationError",
    "RagService",
    "ResourceAttributes",
    "RetrievalCandidate",
    "RetrievalResult",
    "RetrievedPassage",
    "Role",
    "ScanResult",
    "Skill",
    "Tenant",
    "TenantKind",
    "ToolCapability",
    "ToolErrorCode",
    "ToolExecutionError",
    "ToolRisk",
]
