apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  annotations:
    iam.gke.io/gcp-service-account: cp-reference-api@replace-with-project.iam.gserviceaccount.com
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  annotations:
    iam.gke.io/gcp-service-account: cp-reference-web@replace-with-project.iam.gserviceaccount.com
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration
  annotations:
    iam.gke.io/gcp-service-account: cp-reference-migration@replace-with-project.iam.gserviceaccount.com
automountServiceAccountToken: false
